export const STATUS = { PASS: "PASS", FAIL: "FAIL", PENDING: "PENDING", WAIVER: "WAIVER" };
export const CATEGORIES = { OFFENSIVE: "OFFENSIVE", DEFENSIVE: "DEFENSIVE", DUAL_USE: "DUAL-USE" };
export const CRITERIA_KEYS = [
  { key: "funded", label: "Funded", short: "FND" },
  { key: "dowContract", label: "DoW Contract Vehicle", short: "DoW" },
  { key: "blueSuasNdaa", label: "Blue sUAS / NDAA", short: "BLU" },
  { key: "jagReview", label: "JAG Review", short: "JAG" },
  { key: "muaTechAssess", label: "MUA / Tech Assessment", short: "MUA" },
  { key: "warfighterCapability", label: "Warfighter Capability", short: "CAP" },
  { key: "centcomReady", label: "CENTCOM AOR Ready", short: "AOR" },
];
export const SAMPLE_PLATFORMS = [
  { id:"SYS-001",name:"Coyote Block 3",manufacturer:"Raytheon / RTX",category:"DEFENSIVE",subcategory:"Kinetic Interceptor",description:"Tube-launched C-sUAS interceptor with autonomous target engagement.",trl:9,unitCost:82000,qty:340,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Operational with Army C-sUAS units. LRIP complete."},
  { id:"SYS-002",name:"MORFIUS",manufacturer:"Lockheed Martin",category:"DEFENSIVE",subcategory:"HPM / Directed Energy",description:"High-powered microwave effector drone. Single-use EW interceptor.",trl:7,unitCost:145000,qty:60,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PENDING",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PENDING"},notes:"HPM DE effects under JAG review."},
  { id:"SYS-003",name:"CORIAN",manufacturer:"Applied Physical Sciences (General Dynamics)",category:"DEFENSIVE",subcategory:"Acoustic Detection",description:"Passive acoustic detection array for sUAS early warning.",trl:8,unitCost:38000,qty:120,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Fielded to multiple CENTCOM locations."},
  { id:"SYS-004",name:"DroneDefender V2",manufacturer:"Dedrone (Axon)",category:"DEFENSIVE",subcategory:"RF Jammer / Handheld",description:"Handheld directional RF jammer for C2 and GPS disruption.",trl:9,unitCost:32000,qty:500,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Widely fielded. Minimal training footprint."},
  { id:"SYS-005",name:"LIDS",manufacturer:"SAIC / Northrop Grumman",category:"DEFENSIVE",subcategory:"Integrated C-sUAS Suite",description:"Multi-sensor, multi-effector integrated air defense system.",trl:8,unitCost:8500000,qty:18,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Primary Army C-sUAS fixed-site system."},
  { id:"SYS-006",name:"Skyview AI Tracker",manufacturer:"Anduril Industries",category:"DEFENSIVE",subcategory:"AI-Enabled Detection",description:"AI/ML-powered autonomous detection and tracking.",trl:8,unitCost:275000,qty:85,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Lattice OS integration."},
  { id:"SYS-007",name:"FS-LIDS EW Module",manufacturer:"SRC Inc.",category:"DEFENSIVE",subcategory:"Electronic Warfare",description:"Fixed-site EW jamming module for commercial sUAS protocols.",trl:7,unitCost:620000,qty:28,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PENDING",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PENDING"},notes:"EW spectrum coordination required."},
  { id:"SYS-010",name:"Switchblade 600",manufacturer:"AeroVironment",category:"OFFENSIVE",subcategory:"Loitering Munition",description:"Man-portable anti-armor loitering munition with Javelin-class warhead.",trl:9,unitCost:55000,qty:1200,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Combat proven. Full-rate production."},
  { id:"SYS-011",name:"Switchblade 300",manufacturer:"AeroVironment",category:"OFFENSIVE",subcategory:"Loitering Munition",description:"Miniature loitering munition for anti-personnel engagement.",trl:9,unitCost:6000,qty:4500,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Widely fielded. SOF and conventional."},
  { id:"SYS-012",name:"ALTIUS-600",manufacturer:"Anduril Industries",category:"OFFENSIVE",subcategory:"Modular UAS / Strike",description:"Tube-launched modular Group 2 UAS. ISR, EW, and strike payloads.",trl:8,unitCost:150000,qty:320,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Lattice-integrated. Multi-domain launch."},
  { id:"SYS-013",name:"Phoenix Ghost",manufacturer:"Aevex Aerospace",category:"OFFENSIVE",subcategory:"Loitering Munition",description:"Purpose-built loitering munition via USSOCOM rapid acquisition.",trl:8,unitCost:95000,qty:180,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PENDING"},notes:"CENTCOM deployment pending logistics."},
  { id:"SYS-014",name:"Coyote Block 2+",manufacturer:"Raytheon / RTX",category:"DUAL-USE",subcategory:"Interceptor / Strike",description:"Dual-role variant for C-sUAS intercept and limited offensive strike.",trl:7,unitCost:98000,qty:110,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PENDING",muaTechAssess:"PENDING",warfighterCapability:"PASS",centcomReady:"PENDING"},notes:"Dual-use ROE under JAG review."},
  { id:"SYS-015",name:"Puma 3 AE",manufacturer:"AeroVironment",category:"OFFENSIVE",subcategory:"ISR / Targeting",description:"Hand-launched Group 1 ISR UAS for targeting and BDA.",trl:9,unitCost:42000,qty:2800,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Blue sUAS listed. Standard-issue."},
  { id:"SYS-016",name:"RQ-20B Puma II",manufacturer:"AeroVironment",category:"OFFENSIVE",subcategory:"ISR / Targeting",description:"Legacy hand-launched ISR platform with AES-256 encryption.",trl:9,unitCost:38000,qty:1400,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Proven platform. Sustainment contracts in place."},
  { id:"SYS-017",name:"JUMP 20",manufacturer:"L3Harris / Textron",category:"OFFENSIVE",subcategory:"VTOL ISR / Strike",description:"Group 3 VTOL-capable fixed-wing UAS with optional precision munitions.",trl:7,unitCost:380000,qty:45,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PENDING",muaTechAssess:"PENDING",warfighterCapability:"PASS",centcomReady:"PENDING"},notes:"FTUAS candidate. Strike integration under assessment."},
  { id:"SYS-018",name:"Stalker XE",manufacturer:"Lockheed Martin",category:"OFFENSIVE",subcategory:"Persistent ISR",description:"Silent electric Group 2 UAS with 8+ hour endurance.",trl:8,unitCost:125000,qty:95,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"SOF employment. Low signature."},
  { id:"SYS-020",name:"THOR",manufacturer:"AFRL / Leidos",category:"DEFENSIVE",subcategory:"Directed Energy / HPM",description:"Containerized high-power microwave for base defense against swarms.",trl:7,unitCost:18000000,qty:4,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PENDING",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PENDING"},notes:"AFRL rapid prototyping."},
  { id:"SYS-021",name:"Roadrunner",manufacturer:"Anduril Industries",category:"DEFENSIVE",subcategory:"Reusable Interceptor",description:"Jet-powered reusable C-sUAS interceptor with autonomous VTOL.",trl:7,unitCost:200000,qty:65,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PENDING",warfighterCapability:"PASS",centcomReady:"PENDING"},notes:"Reusable airframe. MUA in progress."},
  { id:"SYS-022",name:"SkyDome 300",manufacturer:"D-Fend Solutions",category:"DEFENSIVE",subcategory:"Cyber Takeover",description:"RF cyber-takeover C-sUAS system forcing controlled landing.",trl:8,unitCost:950000,qty:22,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"WAIVER",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Israeli origin — NDAA waiver in effect."},
  { id:"SYS-023",name:"Dronebuster V3i",manufacturer:"Flex Force Enterprises",category:"DEFENSIVE",subcategory:"Handheld Jammer",description:"Handheld C-sUAS jammer with integrated GPS spoofing.",trl:9,unitCost:45000,qty:650,compliance:{funded:"PASS",dowContract:"PASS",blueSuasNdaa:"PASS",jagReview:"PASS",muaTechAssess:"PASS",warfighterCapability:"PASS",centcomReady:"PASS"},notes:"Highest fielding numbers for handheld C-sUAS."},
];
