// ── sampleData.js ───────────────────────────────────────────────────────────
// Fallback dataset used when no Google Sheet URL is configured.
// This file is never modified at runtime — it exists solely as a
// demonstration baseline and offline fallback.
// ─────────────────────────────────────────────────────────────────────────────

export const STATUS = {
  PASS: "PASS",
  FAIL: "FAIL",
  PENDING: "PENDING",
  WAIVER: "WAIVER",
};

export const CATEGORIES = {
  OFFENSIVE: "OFFENSIVE",
  DEFENSIVE: "DEFENSIVE",
  DUAL_USE: "DUAL-USE",
};

export const CRITERIA_KEYS = [
  { key: "funded", label: "Funded", short: "FND" },
  { key: "dowContract", label: "DoW Contract Vehicle", short: "DoW" },
  { key: "blueSuasNdaa", label: "Blue sUAS / NDAA", short: "BLU" },
  { key: "jagReview", label: "JAG Review", short: "JAG" },
  { key: "muaTechAssess", label: "MUA / Tech Assessment", short: "MUA" },
  { key: "warfighterCapability", label: "Warfighter Capability", short: "CAP" },
  { key: "centcomReady", label: "CENTCOM AOR Ready", short: "AOR" },
];

export const SAMPLE_PLATFORMS = [
  {
    id: "SYS-001",
    name: "Coyote Block 3",
    manufacturer: "Raytheon / RTX",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Kinetic Interceptor",
    description:
      "Tube-launched C-sUAS interceptor with autonomous target engagement. Deploys from LIDS and KuRFS-paired launchers.",
    trl: 9,
    unitCost: 82000,
    qty: 340,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Operational with Army C-sUAS units. LRIP complete.",
  },
  {
    id: "SYS-002",
    name: "MORFIUS",
    manufacturer: "Lockheed Martin",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "HPM / Directed Energy",
    description:
      "High-powered microwave (HPM) effector drone. Single-use EW interceptor neutralizes swarms via directed energy pulse.",
    trl: 7,
    unitCost: 145000,
    qty: 60,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PENDING,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PENDING,
    },
    notes: "HPM DE effects under JAG review for collateral damage risk in congested AOR.",
  },
  {
    id: "SYS-003",
    name: "CORIAN",
    manufacturer: "Applied Physical Sciences (General Dynamics)",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Acoustic Detection",
    description:
      "Passive acoustic detection array for sUAS early warning. Integrates with FAAD C2 for cueing kinetic/EW effectors.",
    trl: 8,
    unitCost: 38000,
    qty: 120,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Fielded to multiple CENTCOM locations. Sensor-only, no effector.",
  },
  {
    id: "SYS-004",
    name: "DroneDefender V2",
    manufacturer: "Dedrone (Axon)",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "RF Jammer / Handheld",
    description:
      "Handheld directional RF jammer. Disrupts C2 and GPS links on threat sUAS at ranges up to 400m.",
    trl: 9,
    unitCost: 32000,
    qty: 500,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Widely fielded. Individual operator employment. Minimal training footprint.",
  },
  {
    id: "SYS-005",
    name: "LIDS",
    manufacturer: "SAIC / Northrop Grumman",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Integrated C-sUAS Suite",
    description:
      "Multi-sensor, multi-effector integrated air defense system. Combines radar, EO/IR, EW jamming, and Coyote interceptors.",
    trl: 8,
    unitCost: 8500000,
    qty: 18,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Primary Army C-sUAS fixed-site system. Block upgrades ongoing.",
  },
  {
    id: "SYS-006",
    name: "Skyview AI Tracker",
    manufacturer: "Anduril Industries",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "AI-Enabled Detection",
    description:
      "AI/ML-powered autonomous detection and tracking. Lattice-integrated sensor fusion for real-time sUAS classification.",
    trl: 8,
    unitCost: 275000,
    qty: 85,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Lattice OS integration enables multi-domain sensor fusion.",
  },
  {
    id: "SYS-007",
    name: "FS-LIDS EW Module",
    manufacturer: "SRC Inc.",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Electronic Warfare",
    description:
      "Fixed-site electronic warfare jamming module. Provides wideband RF defeat capability against commercial sUAS protocols.",
    trl: 7,
    unitCost: 620000,
    qty: 28,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PENDING,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PENDING,
    },
    notes: "EW spectrum management coordination required with host-nation.",
  },
  {
    id: "SYS-010",
    name: "Switchblade 600",
    manufacturer: "AeroVironment",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "Loitering Munition",
    description:
      "Man-portable anti-armor loitering munition. Javelin-class warhead with 40+ min endurance and precision strike capability.",
    trl: 9,
    unitCost: 55000,
    qty: 1200,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Combat proven. FMS authorized. Full-rate production.",
  },
  {
    id: "SYS-011",
    name: "Switchblade 300",
    manufacturer: "AeroVironment",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "Loitering Munition",
    description:
      "Miniature loitering munition for anti-personnel engagement. Backpackable, tube-launched with EO/IR guidance.",
    trl: 9,
    unitCost: 6000,
    qty: 4500,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Widely fielded. SOF and conventional force employment.",
  },
  {
    id: "SYS-012",
    name: "ALTIUS-600",
    manufacturer: "Anduril Industries",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "Modular UAS / Strike",
    description:
      "Tube-launched modular Group 2 UAS. Supports ISR, EW, and strike payloads. Air-launchable from C-130 and MQ-9.",
    trl: 8,
    unitCost: 150000,
    qty: 320,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Lattice-integrated. Multi-domain launch capable.",
  },
  {
    id: "SYS-013",
    name: "Phoenix Ghost",
    manufacturer: "Aevex Aerospace",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "Loitering Munition",
    description:
      "Purpose-built loitering munition developed under USSOCOM rapid acquisition. Extended endurance for persistent strike.",
    trl: 8,
    unitCost: 95000,
    qty: 180,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PENDING,
    },
    notes: "Rapid fielding pathway. CENTCOM deployment pending logistics package.",
  },
  {
    id: "SYS-014",
    name: "Coyote Block 2+",
    manufacturer: "Raytheon / RTX",
    category: CATEGORIES.DUAL_USE,
    subcategory: "Interceptor / Strike",
    description:
      "Dual-role variant supporting both C-sUAS intercept and limited offensive strike against soft targets.",
    trl: 7,
    unitCost: 98000,
    qty: 110,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PENDING,
      muaTechAssess: STATUS.PENDING,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PENDING,
    },
    notes: "Dual-use ROE under JAG review. MUA for offensive role in progress.",
  },
  {
    id: "SYS-015",
    name: "Puma 3 AE",
    manufacturer: "AeroVironment",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "ISR / Targeting",
    description:
      "Hand-launched Group 1 ISR UAS. Provides real-time targeting data and BDA for fires coordination.",
    trl: 9,
    unitCost: 42000,
    qty: 2800,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Blue sUAS listed. Standard-issue for BCT ISR sections.",
  },
  {
    id: "SYS-016",
    name: "RQ-20B Puma II",
    manufacturer: "AeroVironment",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "ISR / Targeting",
    description:
      "Legacy hand-launched ISR platform. Digital data link with AES-256 encryption. Night capable with IR payload.",
    trl: 9,
    unitCost: 38000,
    qty: 1400,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Proven platform. Sustainment contracts in place.",
  },
  {
    id: "SYS-017",
    name: "JUMP 20",
    manufacturer: "L3Harris / Textron",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "VTOL ISR / Strike",
    description:
      "Group 3 VTOL-capable fixed-wing UAS. Extended range ISR with optional precision munition payload.",
    trl: 7,
    unitCost: 380000,
    qty: 45,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PENDING,
      muaTechAssess: STATUS.PENDING,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PENDING,
    },
    notes: "FTUAS candidate. Strike payload integration under assessment.",
  },
  {
    id: "SYS-018",
    name: "Stalker XE",
    manufacturer: "Lockheed Martin",
    category: CATEGORIES.OFFENSIVE,
    subcategory: "Persistent ISR",
    description:
      "Silent electric Group 2 UAS. 8+ hour endurance for persistent surveillance and target development in denied areas.",
    trl: 8,
    unitCost: 125000,
    qty: 95,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "SOF employment. Low acoustic/visual signature.",
  },
  {
    id: "SYS-020",
    name: "THOR",
    manufacturer: "AFRL / Leidos",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Directed Energy / HPM",
    description:
      "Containerized high-power microwave system for base defense. Defeats sUAS swarms with wide-beam RF energy.",
    trl: 7,
    unitCost: 18000000,
    qty: 4,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PENDING,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PENDING,
    },
    notes: "AFRL rapid prototyping. Deployed for operational assessment.",
  },
  {
    id: "SYS-021",
    name: "Roadrunner",
    manufacturer: "Anduril Industries",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Reusable Interceptor",
    description:
      "Jet-powered reusable C-sUAS interceptor. Autonomous VTOL launch/recovery with kinetic defeat capability.",
    trl: 7,
    unitCost: 200000,
    qty: 65,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PENDING,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PENDING,
    },
    notes: "Reusable airframe reduces cost-per-engagement. MUA in progress.",
  },
  {
    id: "SYS-022",
    name: "SkyDome 300",
    manufacturer: "D-Fend Solutions",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Cyber Takeover",
    description:
      "RF cyber-takeover C-sUAS system. Non-kinetic protocol exploitation forces controlled landing of threat UAS.",
    trl: 8,
    unitCost: 950000,
    qty: 22,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.WAIVER,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Israeli origin — NDAA waiver in effect. Cyber-takeover capability unique.",
  },
  {
    id: "SYS-023",
    name: "Dronebuster V3i",
    manufacturer: "Flex Force Enterprises",
    category: CATEGORIES.DEFENSIVE,
    subcategory: "Handheld Jammer",
    description:
      "Handheld C-sUAS jammer with integrated GPS spoofing. Point-and-defeat engagement for dismounted operators.",
    trl: 9,
    unitCost: 45000,
    qty: 650,
    compliance: {
      funded: STATUS.PASS,
      dowContract: STATUS.PASS,
      blueSuasNdaa: STATUS.PASS,
      jagReview: STATUS.PASS,
      muaTechAssess: STATUS.PASS,
      warfighterCapability: STATUS.PASS,
      centcomReady: STATUS.PASS,
    },
    notes: "Highest fielding numbers for handheld C-sUAS. GPS spoof mode.",
  },
];
